server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
        - id: service-service
          uri: lb://service-service
          predicates:
            - Path=/api/v1/service/**
        - id: package-service
          uri: lb://package-service
          predicates:
                - Path=/api/v1/package/**

