server:
  port: 8082
  servlet:
  context-path: /api/v1/user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/fact-db
    username: postgres
    password: contrasegol
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
